export const Item_Props = [
  {
    id: 0,
    label: 'Plant',
    options: 'plants',
  },
  {
    id: 1,
    label: 'Fertilizer',
    options: 'fertilizers',
    cardColor: '#F47E3E',
    iconColor: '#F69865',
    icon: 'flower-pollen-outline',
    titleColor: 'white',
  },
  {
    id: 2,
    label: 'Pesticide',
    options: 'pesticides',
    cardColor: '#3870A8',
    iconColor: '#6699CC',
    icon: 'bug',
    titleColor: 'white',
  },
  {
    id: 3,
    label: 'Foliar',
    options: 'foliars',
    cardColor: '#48A9A6',
    iconColor: '#7EC8C5',
    icon: 'leaf',
    titleColor: 'white',
  },
  {
    id: 4,
    label: 'Fungicide',
    options: 'fungicides',
    cardColor: '#BC76BC',
    iconColor: '#D09FD0',
    icon: 'mushroom',
    titleColor: '#fdfffc',
  },
];
