export const Item_Props = [
  {
    id: 0,
    label: 'Plant',
    options: 'plants',
  },
  {
    id: 1,
    label: 'Fertilizer',
    options: 'fertilizers',
    cardColor: '#B4D779',
    softColor: '#EDFFCF',
    iconColor: '#B4D779',
    icon: 'flower-pollen-outline',
    titleColor: 'white',
  },
  {
    id: 2,
    label: 'Pesticide',
    options: 'pesticides',
    cardColor: '#90D77A',
    softColor: '#CCFABE',
    iconColor: '#90D77A',
    icon: 'bug',
    titleColor: 'white',
  },
  {
    id: 3,
    label: 'Foliar',
    options: 'foliars',
    cardColor: '#5DBE5D',
    softColor: '#B9EDB9',
    iconColor: '#5DBE5D',
    icon: 'leaf',
    titleColor: 'white',
  },
  {
    id: 4,
    label: 'Fungicide',
    options: 'fungicides',
    cardColor: '#76D7B0',
    softColor: '#D4FFEE',
    iconColor: '#76D7B0',
    icon: 'mushroom',
    titleColor: '#fdfffc',
  },
];
