export const Item_Props = [
  {
    id: 0,
    label: 'Plant',
    options: 'plants',
  },
  {
    id: 1,
    label: 'Fertilizer',
    options: 'fertilizers',
    cardColor: '#5D9490',
    softColor: '#9BC0BE',
    iconColor: '#5D9490',
    icon: 'flower-pollen-outline',
    titleColor: 'white',
  },
  {
    id: 2,
    label: 'Pesticide',
    options: 'pesticides',
    cardColor: '#765B4B',
    softColor: '#B79E8F',
    iconColor: '#765B4B',
    icon: 'bug',
    titleColor: 'white',
  },
  {
    id: 3,
    label: 'Foliar',
    options: 'foliars',
    cardColor: '#F1C753',
    softColor: '#F8E6B4',
    iconColor: '#F1C753',
    icon: 'leaf',
    titleColor: 'white',
  },
  {
    id: 4,
    label: 'Fungicide',
    options: 'fungicides',
    cardColor: '#1E5883',
    softColor: '#8BBEE5',
    iconColor: '#1E5883',
    icon: 'mushroom',
    titleColor: '#fdfffc',
  },
];
