import {validateRange} from '../utils/field-utils';

export const Summary_Props = [
  {
    id: 0,
    title: 'Aerating',
    action: ['Aerating'],
    icon: 'shovel',
    color: '#FFE4B5',
    type: 'bar',
    unit: 'times',
  },
  {
    id: 1,
    title: 'Sowing',
    action: ['Sowing'],
    icon: 'seed',
    color: 'darkseagreen',
    type: 'stack',
    unit: 'pieces',
  },
  {
    id: 2,
    title: 'Fertilizer Used',
    action: ['Fertilizer'],
    icon: 'flower-pollen-outline',
    color: 'lightblue',
    type: 'stack',
    unit: 'kg/ℓ',
  },
  {
    id: 3,
    title: 'Pesticide Used',
    action: ['Pesticide'],
    icon: 'bug',
    color: 'lavender',
    type: 'stack',
    unit: 'kg/ℓ',
  },
  {
    id: 4,
    title: 'Foliar Used',
    action: ['Foliar'],
    icon: 'leaf',
    color: '#FFB6C1',
    type: 'stack',
    unit: 'kg/ℓ',
  },
  {
    id: 5,
    title: 'Fungicide Used',
    action: ['Fungicide'],
    icon: 'mushroom',
    color: '#FFA07A',
    type: 'stack',
    unit: 'kg/ℓ',
  },
  {
    id: 6,
    title: 'Harvest',
    action: ['Harvest'],
    icon: 'sickle',
    color: 'mintgreen',
    type: 'stack',
    unit: 'pieces',
  },

  {
    id: 7,
    title: 'Transplant',
    action: ['Transplant'],
    icon: 'swap-horizontal',
    color: 'greenyellow',
    type: 'stack',
    unit: 'pieces',
  },
  {
    id: 8,
    title: 'Others',
    action: ['Others'],
    icon: 'unfold-more-vertical',
    color: 'lightgray',
    type: 'bar',
    unit: 'times',
  },
  {
    id: 9,
    title: 'Total Sales',
    action: ['Sales'],
    icon: 'currency-usd',
    color: '#FFFACD',
    type: 'stack',
    unit: 'RM',
  },
  // {
  //   id: 10,
  //   title: 'Total Expenses',
  //   action: ['Pesticide', 'Fertilizer', 'Foliar', 'Fungicide'],
  //   icon: 'currency-usd',
  //   color: '#E6A8D7',
  //   type: 'line',
  //   unit: 'RM',
  // },
  // {
  //   id: '11',
  //   title: 'Profit/Loss',
  //   action: 'calculate',
  //   color: 'lightgray',
  //   type: 'normal',
  // },
];
